version: '3'


services:
    airflow_postgres_db:
        hostname: airflow_postgres_db
        image: postgres:11.1
        env_file:
          - .env
        ports:
          - 5432:5432
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DATABASE" ]
            interval: 5s
            timeout: 5s
            retries: 5
    airflow_redis_db:
        hostname: airflow_redis_db
        image: redis:6.2-alpine
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 1s
            timeout: 3s
            retries: 30
        volumes:
            - ./redis_data:/data

    airflow-webserver:
        build:
            dockerfile: docker/local/Dockerfile
            context: ../../
        command: /airflow/docker/local/webserver.sh
        env_file:
          - .env
        environment:
            - AIRFLOW__WEBSERVER__BASE_URL=http://0.0.0.0
        ports:
            - 3000:3000
        depends_on:
            airflow_postgres_db:
                condition: service_healthy
        volumes:
            - ../../:/airflow
    airflow-scheduler:
        build:
            dockerfile: docker/local/Dockerfile
            context: ../../
        command: /airflow/docker/local/scheduler.sh
        env_file:
            - .env
        depends_on:
            airflow_postgres_db:
                condition: service_healthy
            airflow_redis_db:
                condition: service_healthy
        volumes:
            - ../../:/airflow
    airflow-worker:
        build:
            dockerfile: docker/local/Dockerfile
            context: ../../
        command: /airflow/docker/local/worker.sh
        env_file:
          - .env
        depends_on:
            airflow_postgres_db:
                condition: service_healthy
            airflow_redis_db:
                condition: service_healthy
        volumes:
            - ../../:/airflow
            - /home/nico-navarro/.ssh:/.ssh
    airflow-triggerer:
        build:
            dockerfile: docker/local/Dockerfile
            context: ../../
        command: /airflow/docker/local/triggerer.sh
        env_file:
            - .env
        depends_on:
            airflow_postgres_db:
                condition: service_healthy
            airflow_redis_db:
                condition: service_healthy
        volumes:
            - ../../:/airflow
            - /home/nico-navarro/.ssh:/.ssh
    airflow-flower:
        build:
            dockerfile: docker/local/Dockerfile
            context: ../../
        command: /airflow/docker/local/flower.sh
        env_file:
            - .env
        ports:
            - 5555:5555
        depends_on:
            airflow_postgres_db:
                condition: service_healthy
            airflow_redis_db:
                condition: service_healthy
        volumes:
            - ../../:/airflow
            - /home/nico-navarro/.ssh:/.ssh